import { boolean, integer, jsonb, numeric, pgTable, serial, text, timestamp, unique } from "drizzle-orm/pg-core";

export const journalEntriesTable = pgTable("levelstory_journal_entries", {
  id: serial("id").primaryKey(),
  evaluationKey: text("evaluation_key"),
  symbol: text("symbol").notNull(),
  contractMonth: text("contract_month"),
  side: text("side").notNull(),
  setup: text("setup").notNull(),
  setupType: text("setup_type"),
  outcome: text("outcome"),
  tradingDate: text("trading_date"),
  trend: text("trend"),
  entryPrice: numeric("entry_price", { precision: 12, scale: 4, mode: "number" }).notNull(),
  exitPrice: numeric("exit_price", { precision: 12, scale: 4, mode: "number" }),
  quantity: integer("quantity").notNull(),
  contracts: integer("contracts"),
  pnl: numeric("pnl", { precision: 12, scale: 2, mode: "number" }),
  grossPnl: numeric("gross_pnl", { precision: 12, scale: 2, mode: "number" }),
  netPnl: numeric("net_pnl", { precision: 12, scale: 2, mode: "number" }),
  fees: numeric("fees", { precision: 12, scale: 2, mode: "number" }),
  slippage: numeric("slippage", { precision: 12, scale: 2, mode: "number" }),
  profitTarget: numeric("profit_target", { precision: 12, scale: 4, mode: "number" }),
  maximumFavorableExcursion: numeric("maximum_favorable_excursion", { precision: 12, scale: 2, mode: "number" }),
  maximumAdverseExcursion: numeric("maximum_adverse_excursion", { precision: 12, scale: 2, mode: "number" }),
  exitReason: text("exit_reason"),
  levels: jsonb("levels"),
  confluences: jsonb("confluences"),
  ntz: jsonb("ntz"),
  breakout: jsonb("breakout"),
  pullback: jsonb("pullback"),
  fibonacci: jsonb("fibonacci"),
  volume: jsonb("volume"),
  patience: jsonb("patience"),
  stops: jsonb("stops"),
  runner: jsonb("runner"),
  passedRules: jsonb("passed_rules"),
  failedRules: jsonb("failed_rules"),
  timeline: jsonb("timeline"),
  execution: jsonb("execution"),
  notes: text("notes").notNull(),
  checklistPassed: boolean("checklist_passed").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  evaluationKeyUnique: unique("levelstory_journal_evaluation_key_unique").on(table.evaluationKey),
}));

export const riskSettingsTable = pgTable("levelstory_risk_settings", {
  id: serial("id").primaryKey(),
  accountSize: numeric("account_size", { precision: 14, scale: 2, mode: "number" }).notNull(),
  riskPercent: numeric("risk_percent", { precision: 6, scale: 3, mode: "number" }).notNull(),
  maxDailyLoss: numeric("max_daily_loss", { precision: 14, scale: 2, mode: "number" }).notNull(),
  dailyLossUsed: numeric("daily_loss_used", { precision: 14, scale: 2, mode: "number" }).notNull().default(0),
  isLocked: boolean("is_locked").notNull().default(false),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const marketDataCandlesTable = pgTable("levelstory_market_data_candles", {
  id: serial("id").primaryKey(),
  provider: text("provider").notNull(),
  dataset: text("dataset"),
  rootSymbol: text("root_symbol").notNull(),
  contractSymbol: text("contract_symbol").notNull(),
  intervalMinutes: integer("interval_minutes").notNull(),
  openTime: timestamp("open_time", { withTimezone: true }).notNull(),
  closeTime: timestamp("close_time", { withTimezone: true }).notNull(),
  open: numeric("open", { precision: 14, scale: 4, mode: "number" }).notNull(),
  high: numeric("high", { precision: 14, scale: 4, mode: "number" }).notNull(),
  low: numeric("low", { precision: 14, scale: 4, mode: "number" }).notNull(),
  close: numeric("close", { precision: 14, scale: 4, mode: "number" }).notNull(),
  volume: numeric("volume", { precision: 18, scale: 4, mode: "number" }),
  bid: numeric("bid", { precision: 14, scale: 4, mode: "number" }),
  ask: numeric("ask", { precision: 14, scale: 4, mode: "number" }),
  bidSize: numeric("bid_size", { precision: 18, scale: 4, mode: "number" }),
  askSize: numeric("ask_size", { precision: 18, scale: 4, mode: "number" }),
  isComplete: boolean("is_complete").notNull(),
  quality: jsonb("quality").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  candleIdentityUnique: unique("levelstory_market_data_candle_identity_unique").on(
    table.provider,
    table.rootSymbol,
    table.contractSymbol,
    table.intervalMinutes,
    table.openTime,
  ),
}));

export type JournalEntry = typeof journalEntriesTable.$inferSelect;
export type RiskSettings = typeof riskSettingsTable.$inferSelect;
export type MarketDataCandle = typeof marketDataCandlesTable.$inferSelect;